[project]
name = "studentlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "authx>=1.4.2",
    "fastapi[standard]>=0.115.12",
    "pyjwt>=2.10.1",
]

[tool.uv.workspace]
members = [
    "app/StudenLab-TestTask",
]
